name: Graph Technologies
favicon: null
layout_spectrum: 0.18037749314680696
typography_spectrum: 0.23031497979536653
title: Machine learning consulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3749177996069193
  lightness: 0.6626644358038902
  saturation: 0.8393535546492785
  rhythmicContrast: 0.48629346303641796
purpose: []
